### ISSUE TITLE
simpler cats possible at 32x64

### ISSUE THREAD

**Issue by hartsantler** [alexis-jacq/Pytorch-Sketch-RNN#10]
https://github.com/hartsantler/Pytorch-Sketch-RNN

I have forked and modified this script to work with the latest pytorch.  I'm not sure if there is a bug in my fixes, i have made the network much smaller 32x64, and after awhile training, i do not see it converge to cat shapes.  I also tried reducing the number of examples batch into the training, from 70,000 to 64, is that where i am going wrong?

https://youtu.be/doaU6xm0xH8

https://youtu.be/r7o8AGnsANY

https://youtu.be/6F0XcZG1RNg

**Comment by thomaskerdreux** [comment]
Hey harsantler,
I have the same issue as you, did you solve it?
Also to run with Cuda I add to do some minor changes..

**Comment by hassony2** [comment]
Hi !

@thomaskerdreux, see [issue 3](https://github.com/alexis-jacq/Pytorch-Sketch-RNN/issues/3) for  training fix.
@hartsantler, the related bug (a missing transpose) is also present in [your code](https://github.com/hartsantler/Pytorch-Sketch-RNN/blob/ba9530dce85127e10256dd08767f06a84443644c/sketch_rnn.py#L243), which might be causing the training failure (the videos you show are similar to what I observe when I leave this bug)

Good luck !

**Comment by alexis-jacq** [comment]
I fixed the issue in question (https://github.com/alexis-jacq/Pytorch-Sketch-RNN/issues/3), now it should work.

**Comment by hartsantler** [comment]
@thomaskerdreux 
I fixed the transpose bug as pointed out by hassony2.  This has improved results, right away, i can see it making better attempts at drawing a cat.  But looks like 32x64 is too small a network to solve this problem, or maybe i need to let it train longer? But its already at epoch 17,000 and not yet converged to clearly and consistently drawing cat like shapes.
https://youtu.be/iKiWtgWnwQk

**Comment by hartsantler** [comment]
I tried a few different options for the hyper parameters, but could not get a 64x64 network to draw as well as i had hoped.  Closing this issue because i'm assuming that it is not possible to get decent results from a 32x64 network, or even a 64x64 net.
https://youtu.be/vMjGkK20pe8
